export const GET_BRANDS = "GET_BRANDS";

export const BRANDS_STATUS = "BRANDS_STATUS";
export const GET_PURCHASE = "GET_PURCHASE";

export const PURCHASE_STATUS = "PURCHASE_STATUS";
export const GET_INFLUENCEUR = "GET_INFLUENCEUR";

export const INFLUENCEUR_STATUS = "INFLUENCEUR_STATUS";